[window]
option_as_alt = "OnlyLeft"
decorations = "Buttonless"
opacity = 0.8
blur = true
padding = { x = 5, y = 5 }
dynamic_padding = true

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 14
